(function(global){
  let session=null, photos=[], index=0, cleanup=[];
  const $=id=>document.getElementById(id);
  const esc=s=>global.esc?global.esc(String(s??'')):String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const title=p=>p?.photoTitle||'ללא כותרת';
  const year=v=>String(v||'').match(/(?:19|20|21)\d{2}/)?.[0]||String(v||'');
  const meta=p=>`${p?.albumTitle||'ללא אלבום'}${year(p?.photoDate)?' • '+year(p.photoDate):''}`;
  function template(){return `<section class="section"><div class="heading"><div><span class="eyebrow">התמונות שלי</span><h1>♥ המועדפים שלי</h1><p>כאן ניתן להסיר תמונות מהמועדפים בלי למחוק אותן מהאלבום.</p></div></div><div id="spaFavStatus" class="dashboard-load-status" role="status" aria-live="polite"></div><div id="spaFavGrid" class="gallery"></div></section><div id="spaFavViewer" class="viewer spa-viewer" aria-hidden="true"><button id="spaFavPrev" type="button" aria-label="הקודם"><svg class="viewer-arrow-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M9 5l7 7-7 7"/></svg></button><img id="spaFavBig" alt=""><button id="spaFavNext" type="button" aria-label="הבא"><svg class="viewer-arrow-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M15 5l-7 7 7 7"/></svg></button><div id="spaFavCaption"></div><div id="spaFavDots" class="viewer-dots" aria-label="ניווט בין התמונות"></div></div><button id="spaFavClose" class="spa-close viewer-close-global" type="button" aria-label="סגור">×</button>`;}
  function render(){const g=$('spaFavGrid');if(!g)return;g.innerHTML=photos.map((p,n)=>`<figure class="photo-card"><div class="photo-wrap"><img src="${esc(p.thumbnailUrl||p.imageUrl||'')}" loading="lazy" decoding="async" referrerpolicy="no-referrer" alt="${esc(title(p))}" role="button" tabindex="0" data-open="${n}"><button class="favorite-btn active" type="button" title="הסר מהמועדפים" aria-label="הסר מהמועדפים" data-remove="${n}">♥</button></div><figcaption><strong>${esc(title(p))}</strong><small>📁 ${esc(meta(p))}</small></figcaption></figure>`).join('')||'<p>אין מועדפים עדיין.</p>';g.querySelectorAll('[data-open]').forEach(el=>{el.onclick=()=>open(+el.dataset.open);el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open(+el.dataset.open);}};});g.querySelectorAll('[data-remove]').forEach(el=>el.onclick=e=>{e.stopPropagation();remove(+el.dataset.remove,el);});}
  function dots(){const d=$('spaFavDots');if(!d)return;d.innerHTML=photos.map((_,n)=>`<button class="viewer-dot ${n===index?'active':''}" type="button" data-dot="${n}" aria-label="תמונה ${n+1} מתוך ${photos.length}"></button>`).join('');d.querySelectorAll('[data-dot]').forEach(el=>el.onclick=()=>open(+el.dataset.dot));d.querySelector('.active')?.scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'});}
  function open(n){if(!photos.length)return;index=(n+photos.length)%photos.length;const p=photos[index];$('spaFavBig').src=p.imageUrl||p.thumbnailUrl||'';$('spaFavBig').alt=title(p);$('spaFavCaption').innerHTML=`<strong>${esc(title(p))}</strong><small>📁 ${esc(meta(p))}</small>`;$('spaFavViewer').classList.add('open');$('spaFavViewer').setAttribute('aria-hidden','false');$('spaFavClose').classList.add('is-visible');document.body.classList.add('viewer-open');dots();}
  function close(){$('spaFavViewer')?.classList.remove('open');$('spaFavViewer')?.setAttribute('aria-hidden','true');$('spaFavClose')?.classList.remove('is-visible');$('spaFavBig')?.removeAttribute('src');if($('spaFavDots'))$('spaFavDots').innerHTML='';document.body.classList.remove('viewer-open');}
  function move(d){if(photos.length)open(index+d);}
  async function remove(n,btn){const p=photos[n];if(!p||btn?.dataset.pending==='1')return;btn.dataset.pending='1';const before=photos.slice();photos.splice(n,1);close();render();global.AppStateSync?.favoriteState?.(p.id,false,p.albumId||'');global.AppStateSync?.favoriteDelta?.(-1);global.API?.cacheRemove?.('favorites','list');try{const r=await global.API.call('toggleFavorite',{token:session.token,photoId:p.id});if(!r?.ok||r.data?.favorite!==false)throw new Error(r?.message||'לא ניתן להסיר מהמועדפים');global.AppDataSync?.setFavorites?.(photos);}catch(e){photos=before;global.AppStateSync?.favoriteState?.(p.id,true,p.albumId||'');global.AppStateSync?.favoriteDelta?.(1);render();global.toast?.(e?.message||'לא ניתן להסיר מהמועדפים','error');}}
  async function mount(outlet){cleanup=[];session=global.SessionManager?.getSession?.()||global.getSession?.();if(!session?.token){location.href='index.html?autoLogin=1&loginRequired=1&return='+encodeURIComponent('index.html#/favorites');return;}outlet.innerHTML=template();
    // R17P2O16: bind viewer controls before the warm-cache fast path. O15 returned
    // early for cached Favorites, leaving X/Esc/arrows without event handlers.
    $('spaFavPrev').onclick=()=>move(-1);$('spaFavNext').onclick=()=>move(1);$('spaFavClose').onclick=close;$('spaFavViewer').onclick=e=>{if(e.target===$('spaFavViewer'))close();};const key=e=>{if(!$('spaFavViewer')?.classList.contains('open'))return;if(e.key==='Escape')close();else if(e.key==='ArrowRight')move(-1);else if(e.key==='ArrowLeft')move(1);};document.addEventListener('keydown',key);cleanup.push(()=>document.removeEventListener('keydown',key));let x=null;const ts=e=>x=e.changedTouches?.[0]?.clientX??null,te=e=>{if(x==null)return;const nx=e.changedTouches?.[0]?.clientX??x,dx=nx-x;x=null;if(Math.abs(dx)>45)move(dx>0?-1:1);};$('spaFavViewer').addEventListener('touchstart',ts,{passive:true});$('spaFavViewer').addEventListener('touchend',te,{passive:true});cleanup.push(()=>{$('spaFavViewer')?.removeEventListener('touchstart',ts);$('spaFavViewer')?.removeEventListener('touchend',te);close();});
    const stateFav=global.AppState?.getData?.('favorites');const cached=Array.isArray(stateFav)?stateFav:global.API?.cacheGet?.('favorites','list',600000);if(Array.isArray(cached)){photos=cached;render();$('spaFavStatus').textContent='';return ()=>cleanup.splice(0).forEach(fn=>{try{fn();}catch(_){}});}else{$('spaFavGrid').innerHTML='';$('spaFavStatus').textContent='טוען מועדפים...';$('spaFavStatus').className='dashboard-load-status loading';}try{const r=await global.API.call('favorites',{token:session.token},'GET');if(!r?.ok)throw new Error(r?.message||'לא ניתן לטעון מועדפים');photos=Array.isArray(r.data)?r.data:[];global.AppDataSync?.setFavorites?.(photos);render();$('spaFavStatus').textContent='';}catch(e){if(!Array.isArray(cached))$('spaFavGrid').innerHTML=`<p>${esc(e?.message||'לא ניתן לטעון מועדפים')}</p>`;console.error(e);}
    return ()=>cleanup.splice(0).forEach(fn=>{try{fn();}catch(_){}});}
  function replaceCache(list){photos=Array.isArray(list)?list.slice():[];render();}
  global.SPAFavorites={mount,replaceCache};
})(window);
