(function(global){
  let outlet=null,session=null,data={items:[],options:{}},loaded=false,filters={status:'הכל',type:'הכל',area:'הכל',q:''},sortBy='createdAt',sortDir='desc';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const isAdmin=()=>String(session?.user?.role||'').toUpperCase()==='ADMIN';
  const currentUserId=()=>String(session?.user?.userId||session?.user?.id||session?.userId||'');
  const canOwn= r=>isAdmin()||String(r?.reporterId||'')===currentUserId();
  function formatDT(v){if(!v)return '';const d=new Date(v);if(isNaN(d))return String(v);const parts=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Jerusalem',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(d);const g=t=>parts.find(x=>x.type===t)?.value||'';return `${g('day')}/${g('month')}/${g('year')} ${g('hour')}:${g('minute')}`;}
  function cmp(a,b){if(sortBy==='createdAt')return (new Date(a.createdAt).getTime()||0)-(new Date(b.createdAt).getTime()||0);if(sortBy==='ticketNo')return (Number(a.ticketNo)||0)-(Number(b.ticketNo)||0);return String(a?.[sortBy]||'').localeCompare(String(b?.[sortBy]||''),'he',{numeric:true,sensitivity:'base'});}
  function opts(key,all=true,allLabel='הכל'){const a=data.options?.[key]||[];return (all?[allLabel,...a]:a).map((v,i)=>`<option value="${esc(i===0&&all?v==='הכל'?v:v:v)}">${esc(v)}</option>`).join('');}
  function filterOpts(key,label){const a=data.options?.[key]||[];return [`<option value="הכל">${esc(label)}</option>`,...a.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`)].join('');}
  function visible(){const q=filters.q.toLowerCase();return (data.items||[]).filter(r=>(filters.status==='הכל'||r.status===filters.status)&&(filters.type==='הכל'||r.type===filters.type)&&(filters.area==='הכל'||r.area===filters.area)&&(!q||[r.reporterName,r.description,r.adminNote].join(' ').toLowerCase().includes(q))).sort((a,b)=>cmp(a,b)*(sortDir==='asc'?1:-1));}
  function render(){const rows=visible(),open=(data.items||[]).filter(r=>r.status!=='בוצע').length,done=(data.items||[]).filter(r=>r.status==='בוצע').length;
    outlet.innerHTML=`<main class="section feedback-page"><div class="heading"><div><span class="eyebrow">מעקב</span><h1>מעקב תקלות ושיפורים</h1><p>כאן אפשר לדווח על תקלה, להציע שיפור או לבקש תוספת למערכת.</p></div><div class="feedback-actions"><button class="btn feedback-primary-action" id="fbNew"><span class="feedback-action-icon" aria-hidden="true">＋</span><span>דיווח חדש</span></button><button class="btn secondary feedback-export-action" id="fbExport"><span class="feedback-action-icon" aria-hidden="true">⇩</span><span>ייצוא לאקסל</span></button></div></div>
    <div class="feedback-counters"><button data-status="הכל">סה״כ <b>${data.items.length}</b></button><button data-status="לא בוצע">לא בוצע <b>${open}</b></button><button data-status="בוצע">בוצע <b>${done}</b></button></div>
    <div class="feedback-filters"><label><span>סטטוס</span><select id="fbStatus">${filterOpts('status','כל הסטטוסים')}</select></label><label><span>סוג דיווח</span><select id="fbType">${filterOpts('type','כל הסוגים')}</select></label><label><span>אזור במערכת</span><select id="fbArea">${filterOpts('area','כל האזורים')}</select></label><label class="feedback-search"><span>חיפוש</span><input id="fbQ" placeholder="חיפוש בתיאור או בשם המדווח" value="${esc(filters.q)}"></label><label class="feedback-mobile-sort"><span>מיון לפי</span><select id="fbSortBy"><option value="createdAt">תאריך ושעה</option><option value="ticketNo">מספר</option><option value="reporterName">מדווח</option><option value="type">סוג</option><option value="area">אזור</option><option value="description">תיאור</option><option value="severity">חומרה</option><option value="status">סטטוס</option></select></label><label class="feedback-mobile-sort"><span>סדר</span><select id="fbSortDir"><option value="desc">↓ יורד</option><option value="asc">↑ עולה</option></select></label></div>
    <div class="feedback-table-wrap"><table class="feedback-table"><thead><tr>${[['ticketNo','#'],['createdAt','תאריך ושעה'],['reporterName','מדווח'],['type','סוג'],['area','אזור'],['description','תיאור'],['severity','חומרה'],['status','סטטוס']].map(x=>`<th><button class="feedback-sort" data-sort="${x[0]}">${x[1]} <span class="sort-arrow">↕</span></button></th>`).join('')}<th>פעולות</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td data-label="מספר">${esc(r.ticketNo||i+1)}</td><td data-label="תאריך ושעה">${esc(formatDT(r.createdAt))}</td><td data-label="מדווח">${esc(r.reporterName)}</td><td data-label="סוג">${esc(r.type)}</td><td data-label="אזור">${esc(r.area)}</td><td data-label="תיאור" class="fb-desc">${esc(r.description)}</td><td data-label="חומרה">${esc(r.severity)}</td><td data-label="סטטוס">${esc(r.status)}</td><td data-label="פעולות" class="feedback-row-actions">${canOwn(r)?`<button class="feedback-icon-btn edit" data-manage="${esc(r.id)}" title="עריכה" aria-label="עריכה">✎</button><button class="feedback-icon-btn delete" data-delete="${esc(r.id)}" title="מחיקה" aria-label="מחיקה">🗑</button>`:''}</td></tr>`).join('')||'<tr><td colspan="9" class="muted">אין דיווחים להצגה</td></tr>'}</tbody></table></div></main><div id="fbModal"></div>`;
    ['status','type','area'].forEach(k=>{const e=outlet.querySelector('#fb'+k[0].toUpperCase()+k.slice(1));if(e)e.value=filters[k]});const sb=outlet.querySelector('#fbSortBy'),sd=outlet.querySelector('#fbSortDir');if(sb)sb.value=sortBy;if(sd)sd.value=sortDir;updateSortUI();bind(); }
  function updateSortUI(){
    const map={ticketNo:1,createdAt:2,reporterName:3,type:4,area:5,description:6,severity:7,status:8};
    outlet.querySelectorAll('.feedback-table th').forEach(th=>{th.classList.remove('sorted');th.removeAttribute('aria-sort')});
    outlet.querySelectorAll('.feedback-sort').forEach(b=>{b.classList.toggle('active',b.dataset.sort===sortBy);const a=b.querySelector('.sort-arrow');if(a)a.textContent=b.dataset.sort===sortBy?(sortDir==='asc'?'↑':'↓'):'↕';if(b.dataset.sort===sortBy){const th=b.closest('th');th?.classList.add('sorted');th?.setAttribute('aria-sort',sortDir==='asc'?'ascending':'descending')}});
    outlet.querySelectorAll('.feedback-table tbody td.sorted-col').forEach(td=>{td.classList.remove('sorted-col');delete td.dataset.sortDir});
    const col=map[sortBy];if(col)outlet.querySelectorAll(`.feedback-table tbody tr td:nth-child(${col})`).forEach(td=>{td.classList.add('sorted-col');td.dataset.sortDir=sortDir});
  }
  const busy=(text)=>`<span class="spa-inline-spinner" aria-hidden="true"></span><span>${text}</span>`;
  function modal(html){outlet.querySelector('#fbModal').innerHTML=`<div class="modal open feedback-modal" aria-hidden="false"><div class="modal-card"><button class="modal-close" data-close>×</button>${html}</div></div>`;outlet.querySelector('[data-close]').onclick=()=>outlet.querySelector('#fbModal').innerHTML='';}
  function newReport(){modal(`<h2>דיווח חדש</h2><p class="feedback-help">בחרו את סוג הדיווח והאזור במערכת, ותארו בקצרה מה קרה או מה הייתם רוצים לשנות.</p><div class="feedback-form"><label>סוג דיווח *<select id="nType">${opts('type',false)}</select></label><label>אזור במערכת *<select id="nArea">${opts('area',false)}</select></label><label class="wide">תיאור *<textarea id="nDesc" placeholder="כתבו כאן את פרטי הדיווח"></textarea></label></div><div id="fbMsg" class="form-message"></div><button class="btn" id="fbSave">שמור דיווח</button>`);outlet.querySelector('#fbSave').onclick=saveNew;}
  async function saveNew(){const b=outlet.querySelector('#fbSave'),msg=outlet.querySelector('#fbMsg');b.disabled=true;b.innerHTML=busy('שומר...');try{const r=await API.call('createFeedback',{token:session.token,type:outlet.querySelector('#nType').value,area:outlet.querySelector('#nArea').value,description:outlet.querySelector('#nDesc').value});if(!r?.ok)throw Error(r?.message||'שמירה נכשלה');data.items.unshift(r.data);msg.className='form-message success';msg.textContent='הדיווח נשמר בהצלחה';setTimeout(render,900);}catch(e){msg.className='form-message error';msg.textContent=e.message;}finally{b.disabled=false;b.textContent='שמור דיווח';}}
  function details(id){const r=data.items.find(x=>String(x.id)===String(id));if(!r)return;modal(`<h2>פרטי דיווח</h2><div class="feedback-detail"><b>תאריך ושעה:</b> ${esc(formatDT(r.createdAt))}<br><b>מדווח:</b> ${esc(r.reporterName)}<br><b>סוג:</b> ${esc(r.type)} · <b>אזור:</b> ${esc(r.area)}<hr><b>תיאור</b><p>${esc(r.description)}</p><b>חומרה:</b> ${esc(r.severity)} · <b>סטטוס:</b> ${esc(r.status)}<p><b>הערת טיפול:</b> ${esc(r.adminNote||'-')}</p></div>`);}
  function manage(id){const r=data.items.find(x=>String(x.id)===String(id));if(!r)return;modal(`<h2>עריכת דיווח</h2><div class="feedback-form"><label>סוג דיווח<select id="mType">${opts('type',false)}</select></label><label>אזור במערכת<select id="mArea">${opts('area',false)}</select></label><label class="wide">תיאור<textarea id="mDesc">${esc(r.description||'')}</textarea></label>${isAdmin()?`<label>חומרה<select id="mSeverity">${opts('severity',false)}</select></label><label>סטטוס<select id="mStatus">${opts('status',false)}</select></label><label class="wide">הערת טיפול<textarea id="mNote" placeholder="הערה על הטיפול">${esc(r.adminNote||'')}</textarea></label>`:''}</div><div id="fbMsg" class="form-message"></div><div class="feedback-modal-actions"><button class="btn" id="mSave">שמור שינויים</button></div>`);outlet.querySelector('#mType').value=r.type;outlet.querySelector('#mArea').value=r.area;if(isAdmin()){outlet.querySelector('#mSeverity').value=r.severity;outlet.querySelector('#mStatus').value=r.status;}outlet.querySelector('#mSave').onclick=async()=>{const b=outlet.querySelector('#mSave'),msg=outlet.querySelector('#fbMsg');b.disabled=true;b.innerHTML=busy('שומר...');try{const x=await API.call('updateFeedback',{token:session.token,id:r.id,type:outlet.querySelector('#mType').value,area:outlet.querySelector('#mArea').value,description:outlet.querySelector('#mDesc').value,severity:isAdmin()?outlet.querySelector('#mSeverity').value:undefined,status:isAdmin()?outlet.querySelector('#mStatus').value:undefined,adminNote:isAdmin()?outlet.querySelector('#mNote').value:undefined});if(!x?.ok)throw Error(x?.message||'שמירה נכשלה');Object.assign(r,x.data);msg.className='form-message success';msg.textContent='השינויים נשמרו בהצלחה';setTimeout(render,900);}catch(e){msg.className='form-message error';msg.textContent=e.message;}finally{b.disabled=false;b.textContent='שמור שינויים';}};}
  function confirmDelete(id){const r=data.items.find(x=>String(x.id)===String(id));if(!r)return;modal(`<h2>מחיקת דיווח</h2><p>האם למחוק את דיווח מספר <b>${esc(r.ticketNo||'')}</b>?</p><p class="muted">המחיקה היא סופית.</p><div id="fbMsg" class="form-message"></div><div class="feedback-modal-actions"><button class="btn danger-btn" id="mDeleteConfirm">מחק דיווח</button><button class="btn secondary" data-cancel-delete>ביטול</button></div>`);outlet.querySelector('[data-cancel-delete]').onclick=()=>outlet.querySelector('#fbModal').innerHTML='';outlet.querySelector('#mDeleteConfirm').onclick=async()=>{const b=outlet.querySelector('#mDeleteConfirm'),msg=outlet.querySelector('#fbMsg');b.disabled=true;b.innerHTML=busy('מוחק...');try{const x=await API.call('deleteFeedback',{token:session.token,id:r.id});if(!x?.ok)throw Error(x?.message||'המחיקה נכשלה');data.items=data.items.filter(y=>String(y.id)!==String(r.id));msg.className='form-message success';msg.textContent='הדיווח נמחק בהצלחה';setTimeout(render,900);}catch(e){msg.className='form-message error';msg.textContent=e.message;b.disabled=false;b.textContent='מחק דיווח';}};}
  async function exportXlsx(){const b=outlet.querySelector('#fbExport');b.disabled=true;b.innerHTML=busy('מייצא...');try{const r=await API.call('exportFeedbackXlsx',{token:session.token,...filters});if(!r?.ok)throw Error(r?.message||'ייצוא נכשל');const bin=atob(r.data.base64),u=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)u[i]=bin.charCodeAt(i);const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([u],{type:r.data.mimeType}));a.download=r.data.fileName;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000);}catch(e){alert(e.message);}finally{b.disabled=false;b.innerHTML='<span class="feedback-action-icon" aria-hidden="true">⇩</span><span>ייצוא לאקסל</span>';}}
  function bind(){outlet.querySelector('#fbNew').onclick=newReport;outlet.querySelector('#fbExport').onclick=exportXlsx;outlet.querySelectorAll('[data-status]').forEach(b=>b.onclick=()=>{filters.status=b.dataset.status;render()});[['fbStatus','status'],['fbType','type'],['fbArea','area']].forEach(([id,k])=>outlet.querySelector('#'+id).onchange=e=>{filters[k]=e.target.value;render()});outlet.querySelector('#fbQ').oninput=e=>{filters.q=e.target.value;clearTimeout(global.__fbTimer);global.__fbTimer=setTimeout(render,250)};outlet.querySelectorAll('.feedback-table tbody tr').forEach(tr=>{const id=tr.querySelector('[data-manage],[data-delete]')?.dataset.manage||tr.querySelector('[data-delete]')?.dataset.delete||tr.querySelector('td')?.textContent;if(!id)return;tr.ondblclick=e=>{if(e.target.closest('button'))return;const row=data.items.find(r=>String(r.ticketNo)===String(tr.querySelector('td')?.textContent.trim()))||data.items.find(r=>String(r.id)===String(id));if(row)details(row.id)};tr.onclick=e=>{if(!matchMedia('(max-width:850px)').matches||e.target.closest('button'))return;const row=data.items.find(r=>String(r.ticketNo)===String(tr.querySelector('td')?.textContent.trim()))||data.items.find(r=>String(r.id)===String(id));if(row)details(row.id)}});outlet.querySelectorAll('[data-manage]').forEach(b=>b.onclick=()=>manage(b.dataset.manage));outlet.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>confirmDelete(b.dataset.delete));outlet.querySelectorAll('.feedback-sort').forEach(b=>b.onclick=()=>{const k=b.dataset.sort;if(sortBy===k)sortDir=sortDir==='asc'?'desc':'asc';else{sortBy=k;sortDir='asc'}render()});const sb=outlet.querySelector('#fbSortBy'),sd=outlet.querySelector('#fbSortDir');if(sb)sb.onchange=()=>{sortBy=sb.value;render()};if(sd)sd.onchange=()=>{sortDir=sd.value==='asc'?'asc':'desc';render()};}
  async function mount(o){outlet=o;session=SessionManager?.getSession?.()||getSession?.();const role=String(session?.user?.role||'').toUpperCase();if(!session?.token||!['ADMIN','FAMILY'].includes(role)){outlet.innerHTML='<main class="section"><h2>אין הרשאה</h2></main>';return;}if(loaded){render();return;}outlet.innerHTML='<main class="section"><p class="feedback-loading"><span class="spa-inline-spinner" aria-hidden="true"></span><span>טוען מעקב...</span></p></main>';const r=await API.call('feedback',{token:session.token},'GET');if(!r?.ok)throw Error(r?.message||'טעינת המעקב נכשלה');data=r.data||{items:[],options:{}};loaded=true;render();}
  global.SPAFeedback={mount};
})(window);
